config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  namespace :admin do
    root "dashboard#index"
    get "dashboard" => "dashboard#index", :as => :dashboard
    devise_scope :user do
      get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
      get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration

    end

    devise_for :users, controllers: { sessions: 'admin/users/sessions'}, :passwords => 'admin/users/passwords', :skip => [:registrations]

    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users' => 'devise/registrations#update', :as => 'user_registration'
      patch 'users' => 'devise/registrations#update', :as => 'update_user_registration'
    end

    resources :blogs
    resources :products
    resources :properties
    resources :prototypes

    namespace :changes do
      resources :products do
        resource :property,only: [:edit, :update]
      end
    end
    
    namespace :multi do
      resources :products do
        resource :variant, only: [:edit, :update]
      end
    end


  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable

  enum role: [:user,:staff,:vip,:admin]
  after_initialize :set_default_role, :if => :new_record?

  #instance method
  def set_default_role
    self.role ||= :user
  end

  #Relationship
  has_many :prototypes
  has_many :properties
  has_many :products
  has_many :variants
end

app/controllers/admin/prototypes_controller.rb
class Admin::PrototypesController < ApplicationController
  before_action :authenticate_admin_user!
  before_action :admin_only?
  before_action :set_prototype, only: [:show, :edit, :update, :destroy]

  def index
    @prototypes = Prototype.all
  end

  def show

  end

  def new
    @all_properties = Property.all
    if @all_properties.empty?
      flash[:notice] = "You must create property before you create prototype"
      redirect_to new_admin_property_path
    else
      @prototype = current_admin_user.prototypes.build(active: true)
      @prototype.properties.build
    end
  end

  def create
    @prototype = current_admin_user.prototypes.build(prototype_params)
    if @prototype.save
      @prototype.update_attributes(property_ids: params[:prototype][:property_ids])
      redirect_to admin_prototype_path(@prototype), notice: "Successfully Created"
    else
      @all_properties = Property.all
      flash[:error] = "The prototype could not be saved"
      render :new3
    end
  end

  def edit
    @all_properties = Property.all
    @prototype = Prototype.includes(:properties).find_by_slug(params[:id])
  end

  def update
    @prototype = Prototype.find_by_slug(params[:id])
    @prototype.property_ids = params[:prototype][:property_ids]
    if @prototype.update_attributes(prototype_params)
      redirect_to admin_prototype_path(@prototype), notice: "Successfully Updated"
    else
      @all_properties = Property.all
      render :edit
    end
  end

  private
    def admin_only?
      unless current_admin_user.admin?
        unless @user == current_admin_user
          redirect_to admin_dashboard_path, notice: "You're not able to access this page"
        end
      end
    end

    def set_prototype
      @prototype = Prototype.find_by_slug(params[:id])
    end

    def prototype_params
      params.require(:prototype).permit(:name, :active, :user_id, property_ids: [])
    end

end

app/views/admin/prototypes/_form.html.erb
<div class="wrapper">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
              <div class="page-title-box">
                <h4 class="page-title">Form Prototype</h4>
              </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="card m-b-20">
                    <div class="card-block">
                        <h4 class="mt-0 header-title">Prototype</h4>
                        <p class="text-muted m-b-30 font-14"></p>
                        <%=form_for ([:admin,@prototype]) do |f|%>
                          <%=f.error_messages%>
                            <div class="form-group col-lg-6">
                                <%=f.label :name%>
                                <%=f.text_field :name,class: "form-control", placeholder: "Product Name"%>
                            </div>
                            <div class="form-group col-lg-6">
                                <%=f.label :status, class:"" do%>
                                  <%=f.check_box :active, :class=> ""%>
                                 <span class="custom-control-description"> Active</span>
                                <%end%>
                            </div>
                            <%=render 'property_form'%>
                            <div class="form-group col-lg-6">
                              <div>
                                <%=f.submit :class => "btn btn-info"%>
                                <%=link_to "Cancel", admin_prototypes_path, class:"btn btn-dark"%>
                              </div>
                          </div>
                        <%end%>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/admin/prototypes/_property_form.html.erb
<%@all_properties.each do |property|%>
  <%checked = @prototype.name && @prototype.properties.include?(property)%>
  <%= check_box_tag "prototype[property_ids][]", property.id, checked%>
  <%= property.display_name%> (<%= property.identifing_name%>)
<%end%>

app/views/admin/prototypes/_prototype_detail.html.erb
<div class="wrapper">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
              <div class="page-title-box">
                <h4 class="page-title"><%=@prototype.name%></h4>
              </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="card m-b-20">
                    <div class="card-block">
                        <h4 class="mt-0 header-title">Prototype Detail</h4>
                        <!-- Detail Here -->
                        <%=link_to "Edit", edit_admin_prototype_path, class: "btn btn-info"%>
                        <%=link_to "Cancel", admin_prototypes_path, class: "btn btn-dark"%>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/admin/prototypes/_table_prototype.html.erb
<div class="wrapper">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                  <div class="page-title-box">
                    <div class="btn-group pull-right">
                      <%=link_to "Add New Property", new_admin_property_path, class: "btn btn-large btn-info" %>
                    </div>
                    <h4 class="page-title">Products</h4>
                  </div>
                </div>
            </div>

            <div class="row">
                <div class="col-12">
                    <div class="card m-b-20">
                        <div class="card-block">
                          <h4 class="mt-0 header-title">Products Table</h4>
                            <p class="text-muted m-b-30 font-14"></p>
                            <table id="datatable-buttons" class="table table-striped table-bordered" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Status</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                  <%@prototypes.each do |prototype|%>
                                    <tr>
                                      <td><%=prototype.name%></td>
                                      <td><%=status_converter(prototype.active)%></td>
                                      <td>
                                        <%=link_to "View", admin_prototype_path(prototype)%>
                                        <%=link_to "Edit", edit_admin_prototype_path(prototype)%>
                                        <%=link_to "Delete", admin_prototype_path(prototype), method: :delete, data: {confirm: "Are You Sure ?"}%>
                                      </td>
                                    </tr>
                                  <%end%>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

app/views/admin/prototypes/edit.html.erb
<%= render "components/header"%>

<%=render "form"%>

<%= render "components/footer"%>

<%= render "shared/js-partial/1.bootstrap.min"%>
<%= render "shared/js-partial/2.modernizr.min"%>
<%= render "shared/js-partial/3.waves"%>
<%= render "shared/js-partial/4.jquery.slimscroll"%>
<%= render "shared/js-partial/5.jquery.nicescroll"%>
<%= render "shared/js-partial/6.jquery.scrollTo.min"%>
<%= render "shared/js-partial/7.jquery.dataTables.min"%>
<%= render "shared/js-partial/8.dataTables.bootstrap4.min"%>
<%= render "shared/js-partial/9.dataTables.buttons.min"%>
<%= render "shared/js-partial/10.buttons.bootstrap4.min"%>
<%= render "shared/js-partial/11.jszip.min"%>
<%= render "shared/js-partial/12.pdfmake.min"%>
<%= render "shared/js-partial/13.vfs_fonts"%>
<%= render "shared/js-partial/14.buttons.html5.min"%>
<%= render "shared/js-partial/15.buttons.print.min"%>
<%= render "shared/js-partial/16.buttons.cloVis.min"%>
<%= render "shared/js-partial/17.dataTables.responsive.min"%>
<%= render "shared/js-partial/18.responsive.bootstrap4.min"%>
<%= render "shared/js-partial/19.datatables.init"%>
<%= render "shared/js-partial/20.app"%>

app/views/admin/prototypes/index.html.erb
<%= render "components/header"%>

<%=render "table_prototype"%>

<%= render "components/footer"%>

<%= render "shared/js-partial/1.bootstrap.min"%>
<%= render "shared/js-partial/2.modernizr.min"%>
<%= render "shared/js-partial/3.waves"%>
<%= render "shared/js-partial/4.jquery.slimscroll"%>
<%= render "shared/js-partial/5.jquery.nicescroll"%>
<%= render "shared/js-partial/6.jquery.scrollTo.min"%>
<%= render "shared/js-partial/7.jquery.dataTables.min"%>
<%= render "shared/js-partial/8.dataTables.bootstrap4.min"%>
<%= render "shared/js-partial/9.dataTables.buttons.min"%>
<%= render "shared/js-partial/10.buttons.bootstrap4.min"%>
<%= render "shared/js-partial/11.jszip.min"%>
<%= render "shared/js-partial/12.pdfmake.min"%>
<%= render "shared/js-partial/13.vfs_fonts"%>
<%= render "shared/js-partial/14.buttons.html5.min"%>
<%= render "shared/js-partial/15.buttons.print.min"%>
<%= render "shared/js-partial/16.buttons.cloVis.min"%>
<%= render "shared/js-partial/17.dataTables.responsive.min"%>
<%= render "shared/js-partial/18.responsive.bootstrap4.min"%>
<%= render "shared/js-partial/19.datatables.init"%>
<%= render "shared/js-partial/20.app"%>

app/views/admin/prototypes/new.html.erb
<%= render "components/header"%>

<%=render "form"%>

<%= render "components/footer"%>

<%= render "shared/js-partial/1.bootstrap.min"%>
<%= render "shared/js-partial/2.modernizr.min"%>
<%= render "shared/js-partial/3.waves"%>
<%= render "shared/js-partial/4.jquery.slimscroll"%>
<%= render "shared/js-partial/5.jquery.nicescroll"%>
<%= render "shared/js-partial/6.jquery.scrollTo.min"%>
<%= render "shared/js-partial/7.jquery.dataTables.min"%>
<%= render "shared/js-partial/8.dataTables.bootstrap4.min"%>
<%= render "shared/js-partial/9.dataTables.buttons.min"%>
<%= render "shared/js-partial/10.buttons.bootstrap4.min"%>
<%= render "shared/js-partial/11.jszip.min"%>
<%= render "shared/js-partial/12.pdfmake.min"%>
<%= render "shared/js-partial/13.vfs_fonts"%>
<%= render "shared/js-partial/14.buttons.html5.min"%>
<%= render "shared/js-partial/15.buttons.print.min"%>
<%= render "shared/js-partial/16.buttons.cloVis.min"%>
<%= render "shared/js-partial/17.dataTables.responsive.min"%>
<%= render "shared/js-partial/18.responsive.bootstrap4.min"%>
<%= render "shared/js-partial/19.datatables.init"%>
<%= render "shared/js-partial/20.app"%>

app/views/admin/prototypes/show.html.erb
<%= render "components/header"%>

<%=render "prototype_detail"%>

<%= render "components/footer"%>

<%= render "shared/js-partial/1.bootstrap.min"%>
<%= render "shared/js-partial/2.modernizr.min"%>
<%= render "shared/js-partial/3.waves"%>
<%= render "shared/js-partial/4.jquery.slimscroll"%>
<%= render "shared/js-partial/5.jquery.nicescroll"%>
<%= render "shared/js-partial/6.jquery.scrollTo.min"%>
<%= render "shared/js-partial/7.jquery.dataTables.min"%>
<%= render "shared/js-partial/8.dataTables.bootstrap4.min"%>
<%= render "shared/js-partial/9.dataTables.buttons.min"%>
<%= render "shared/js-partial/10.buttons.bootstrap4.min"%>
<%= render "shared/js-partial/11.jszip.min"%>
<%= render "shared/js-partial/12.pdfmake.min"%>
<%= render "shared/js-partial/13.vfs_fonts"%>
<%= render "shared/js-partial/14.buttons.html5.min"%>
<%= render "shared/js-partial/15.buttons.print.min"%>
<%= render "shared/js-partial/16.buttons.cloVis.min"%>
<%= render "shared/js-partial/17.dataTables.responsive.min"%>
<%= render "shared/js-partial/18.responsive.bootstrap4.min"%>
<%= render "shared/js-partial/19.datatables.init"%>
<%= render "shared/js-partial/20.app"%>