config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  namespace :admin do
    root "dashboard#index"
    get "dashboard" => "dashboard#index", :as => :dashboard
    devise_scope :user do
      get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
      get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration

    end

    devise_for :users, controllers: { sessions: 'admin/users/sessions'}, :passwords => 'admin/users/passwords', :skip => [:registrations]

    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users' => 'devise/registrations#update', :as => 'user_registration'
      patch 'users' => 'devise/registrations#update', :as => 'update_user_registration'
    end

    resources :blogs
    resources :products
    resources :properties
    resources :prototypes

    namespace :changes do
      resources :products do
        resource :property,only: [:edit, :update]
      end
    end
    
    namespace :multi do
      resources :products do
        resource :variant, only: [:edit, :update]
      end
    end


  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  before_save :update_slug

  #Relationship
  has_many :product_properties, inverse_of: :product
  has_many :properties, through: :product_properties

  has_many :product_variants, inverse_of: :product
  has_many :variants, through: :product_properties

  belongs_to :user, required: false
  belongs_to :prototype, required: false

  accepts_nested_attributes_for :product_properties, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :product_variants,reject_if: proc { |attributes| attributes['sku'].blank? }
  def update_slug
    self.slug = product_name.parameterize
  end

  def to_param
    slug
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin_user!
  before_action :admin_only?
  before_action :form_infomation, only: [:new,:create]
  before_action :set_product, only: [:show,:edit,:update,:destroy]

  def index
    @products = Product.all
  end

  def show

  end

  def new
    if @prototypes.empty?
      flash[:notice] = "You must go to create prototype before you create product"
      redirect_to new_admin_prototype_path
    else
      @product = current_admin_user.products.build
      @product.prototype = Prototype.new
    end
  end

  def create
    @product = current_admin_user.products.build(product_params)
    if @product.save
      flash[:notice] = "Successfully Created, You Should Create A Variant For The Product"
      redirect_to edit_admin_product_path(@product)
    else
      flash[:error] = "The product could not be saved"
      render :new
    end
  end

  private
    def admin_only?
      unless current_admin_user.admin?
        unless @user == current_admin_user
          redirect_to admin_dashboard_path, notice: "You're not able to access this page"
        end
      end
    end

    def set_product
      @product = Product.find_by_slug(params[:id])
    end

    def product_params
      params.required(:product).permit(:product_name,:product_keywords,:permalink,:meta_keywords,:meta_description,:user_id,:prototype_id)
    end

    def form_infomation
      @prototypes = Prototype.all.map{|pt| [pt.name, pt.id]}
    end
end

app/views/admin/products/_product_detail.html.erb
<div class="wrapper">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
              <div class="page-title-box">
                <h4 class="page-title"><%=@product.product_name%></h4>
              </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="card m-b-20">
                    <div class="card-block">
                        <h4 class="mt-0 header-title">Product Detail</h4>
                        <!-- Detail Here -->
                        <%=link_to "Edit", edit_admin_product_path, class: "btn btn-info"%>
                        <%=link_to "Cancel", admin_products_path, class: "btn btn-dark"%>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/admin/products/_right_sidebar.html.erb
<div class="col-lg-4">
  <div class="card m-b-20">
    <div class="card-block">
      <div class="email-leftbar">
        <span href="" class="btn btn-danger btn-rounded btn-custom btn-block waves-effect waves-light">Compose</span>
        <div class="mail-list m-t-20">
          <a href="#">Description</a>
          <a href="#">Images</a>
          <%=link_to "Product", edit_admin_product_path%>
          <%=link_to "Properties",edit_admin_changes_product_property_path(@product)%>
          <%= link_to "Variant", edit_admin_multi_product_variant_path(@product)%>
          <a href="#">Inventory</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/_table_product.html.erb
<div class="wrapper">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                  <div class="page-title-box">
                    <div class="btn-group pull-right">
                      <%=link_to "Add New Product", new_admin_product_path, class: "btn btn-large btn-info" %>
                    </div>
                    <h4 class="page-title">Products</h4>
                  </div>
                </div>
            </div>

            <div class="row">
                <div class="col-12">
                    <div class="card m-b-20">
                        <div class="card-block">
                          <h4 class="mt-0 header-title">Products Table</h4>
                            <p class="text-muted m-b-30 font-14"></p>
                            <table id="datatable-buttons" class="table table-striped table-bordered" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Position</th>
                                        <th>Office</th>
                                        <th>Age</th>
                                        <th>Start date</th>
                                        <th>Salary</th>
                                    </tr>
                                </thead>
                                <tbody>
                                  <%@products.each do |product|%>
                                    <tr>
                                      <td><%=product.product_name%></td>
                                      <td><%=product.created_at%></td>
                                      <td><%=product.updated_at%></td>
                                      <td>
                                        <%=link_to "View", admin_product_path(product), class: ""%>
                                        <%=link_to "Edit", edit_admin_product_path(product), class: ""%>
                                        <%=link_to "Delete", admin_product_path(product),class: ""%>
                                      </td>
                                    </tr>
                                  <%end%>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

app/views/admin/products/edit.html.erb
<%=render "components/header"%>

<div class="wrapper">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
              <div class="page-title-box">
                <h4 class="page-title">Form Product</h4>
              </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8">
                <div class="card m-b-20">
                    <div class="card-block">
                        <h4 class="mt-0 header-title">Product</h4>
                        <p class="text-muted m-b-30 font-14">Parsley is a javascript form validation library. It helps you provide your users with feedback on their form submission before sending it to your server.</p>
                        <%=form_for([:admin, @product])do |f|%>
                          <div class="row">
                            <div class="form-group col-lg-4">
                              <%=f.label :product_name%>
                              <%=f.text_field :product_name, class: "form-control", placeholder: "Product Name"%>
                            </div>
                            <div class="form-group col-lg-4">
                              <%=f.label :permalink%>
                              <%=f.text_field :permalink, class: "form-control", placeholder: "Permalink"%>
                            </div>
                            <div class="form-group col-lg-4">
                              <%=f.label :meta_keywords%>
                              <%=f.text_field :meta_keywords, class: "form-control", placeholder: "Meta Keywords"%>
                            </div>
                            <div class="form-group col-lg-4">
                              <%=f.label :meta_description%>
                              <%=f.text_field :meta_description, class: "form-control", placeholder: "Permalink"%>
                            </div>
                            <div class="form-group col-lg-4">
                              <%=f.label :prototype%>
                              <%=f.collection_select :prototype_id,Prototype.all,:id,:name, {prompt: "SELECT Prototype ..."}, {:class=>"form-control"}%>
                            </div>
                          </div>
                          <div class="form-group">
                            <div>
                              <%=f.submit "Submit", class: "btn btn-info"%>
                              <%=link_to "Cancel", admin_products_path, class: "btn btn-dark"%>
                            </div>
                          </div>
                        <%end%>
                    </div>
                </div>
            </div>
            <%=render "right_sidebar"%>
        </div>
    </div>
</div>
<%=render "components/footer"%>
<%= render "shared/js-partial/1.bootstrap.min"%>
<%= render "shared/js-partial/2.modernizr.min"%>
<%= render "shared/js-partial/3.waves"%>
<%= render "shared/js-partial/4.jquery.slimscroll"%>
<%= render "shared/js-partial/5.jquery.nicescroll"%>
<%= render "shared/js-partial/6.jquery.scrollTo.min"%>
<%= render "shared/js-partial/7.jquery.dataTables.min"%>
<%= render "shared/js-partial/8.dataTables.bootstrap4.min"%>
<%= render "shared/js-partial/9.dataTables.buttons.min"%>
<%= render "shared/js-partial/10.buttons.bootstrap4.min"%>
<%= render "shared/js-partial/11.jszip.min"%>
<%= render "shared/js-partial/12.pdfmake.min"%>
<%= render "shared/js-partial/13.vfs_fonts"%>
<%= render "shared/js-partial/14.buttons.html5.min"%>
<%= render "shared/js-partial/15.buttons.print.min"%>
<%= render "shared/js-partial/16.buttons.cloVis.min"%>
<%= render "shared/js-partial/17.dataTables.responsive.min"%>
<%= render "shared/js-partial/18.responsive.bootstrap4.min"%>
<%= render "shared/js-partial/19.datatables.init"%>
<%= render "shared/js-partial/20.app"%>

app/views/admin/products/index.html.erb
<%= render "components/header"%>

<%= render "table_product"%>

<%= render "components/footer"%>

<%= render "shared/js-partial/1.bootstrap.min"%>
<%= render "shared/js-partial/2.modernizr.min"%>
<%= render "shared/js-partial/3.waves"%>
<%= render "shared/js-partial/4.jquery.slimscroll"%>
<%= render "shared/js-partial/5.jquery.nicescroll"%>
<%= render "shared/js-partial/6.jquery.scrollTo.min"%>
<%= render "shared/js-partial/7.jquery.dataTables.min"%>
<%= render "shared/js-partial/8.dataTables.bootstrap4.min"%>
<%= render "shared/js-partial/9.dataTables.buttons.min"%>
<%= render "shared/js-partial/10.buttons.bootstrap4.min"%>
<%= render "shared/js-partial/11.jszip.min"%>
<%= render "shared/js-partial/12.pdfmake.min"%>
<%= render "shared/js-partial/13.vfs_fonts"%>
<%= render "shared/js-partial/14.buttons.html5.min"%>
<%= render "shared/js-partial/15.buttons.print.min"%>
<%= render "shared/js-partial/16.buttons.cloVis.min"%>
<%= render "shared/js-partial/17.dataTables.responsive.min"%>
<%= render "shared/js-partial/18.responsive.bootstrap4.min"%>
<%= render "shared/js-partial/19.datatables.init"%>
<%= render "shared/js-partial/20.app"%>

app/views/admin/products/new.html.erb
<%=render "components/header"%>

<div class="wrapper">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
              <div class="page-title-box">
                <h4 class="page-title">Form Product</h4>
              </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="card m-b-20">
                    <div class="card-block">
                        <h4 class="mt-0 header-title">Product</h4>
                        <p class="text-muted m-b-30 font-14">Parsley is a javascript form validation library. It helps you provide your users with feedback on their form submission before sending it to your server.</p>
                        <%=form_for([:admin, @product])do |f|%>
                          <div class="row">
                            <div class="form-group col-lg-4">
                              <%=f.label :product_name%>
                              <%=f.text_field :product_name, class: "form-control", placeholder: "Product Name"%>
                            </div>
                            <div class="form-group col-lg-4">
                              <%=f.label :permalink%>
                              <%=f.text_field :permalink, class: "form-control", placeholder: "Permalink"%>
                            </div>
                            <div class="form-group col-lg-4">
                              <%=f.label :meta_keywords%>
                              <%=f.text_field :meta_keywords, class: "form-control", placeholder: "Meta Keywords"%>
                            </div>
                            <div class="form-group col-lg-4">
                              <%=f.label :meta_description%>
                              <%=f.text_field :meta_description, class: "form-control", placeholder: "Permalink"%>
                            </div>
                            <div class="form-group col-lg-4">
                              <%=f.label :prototype%>
                              <%=f.collection_select :prototype_id,Prototype.all,:id,:name, {prompt: "SELECT Prototype ..."}, {:class=>"form-control"}%>
                            </div>
                          </div>
                          <div class="form-group">
                            <div>
                              <%=f.submit "Submit", class: "btn btn-info"%>
                              <%=link_to "Cancel", admin_products_path, class: "btn btn-dark"%>
                            </div>
                          </div>
                        <%end%>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<%=render "components/footer"%>

<%= render "shared/js-partial/1.bootstrap.min"%>
<%= render "shared/js-partial/2.modernizr.min"%>
<%= render "shared/js-partial/3.waves"%>
<%= render "shared/js-partial/4.jquery.slimscroll"%>
<%= render "shared/js-partial/5.jquery.nicescroll"%>
<%= render "shared/js-partial/6.jquery.scrollTo.min"%>
<%= render "shared/js-partial/7.jquery.dataTables.min"%>
<%= render "shared/js-partial/8.dataTables.bootstrap4.min"%>
<%= render "shared/js-partial/9.dataTables.buttons.min"%>
<%= render "shared/js-partial/10.buttons.bootstrap4.min"%>
<%= render "shared/js-partial/11.jszip.min"%>
<%= render "shared/js-partial/12.pdfmake.min"%>
<%= render "shared/js-partial/13.vfs_fonts"%>
<%= render "shared/js-partial/14.buttons.html5.min"%>
<%= render "shared/js-partial/15.buttons.print.min"%>
<%= render "shared/js-partial/16.buttons.cloVis.min"%>
<%= render "shared/js-partial/17.dataTables.responsive.min"%>
<%= render "shared/js-partial/18.responsive.bootstrap4.min"%>
<%= render "shared/js-partial/19.datatables.init"%>
<%= render "shared/js-partial/20.app"%>

app/views/admin/products/show.html.erb
<%= render "components/header"%>

<%= render "product_detail"%>

<%= render "components/footer"%>

<%= render "shared/js-partial/1.bootstrap.min"%>
<%= render "shared/js-partial/2.modernizr.min"%>
<%= render "shared/js-partial/3.waves"%>
<%= render "shared/js-partial/4.jquery.slimscroll"%>
<%= render "shared/js-partial/5.jquery.nicescroll"%>
<%= render "shared/js-partial/6.jquery.scrollTo.min"%>
<%= render "shared/js-partial/7.jquery.dataTables.min"%>
<%= render "shared/js-partial/8.dataTables.bootstrap4.min"%>
<%= render "shared/js-partial/9.dataTables.buttons.min"%>
<%= render "shared/js-partial/10.buttons.bootstrap4.min"%>
<%= render "shared/js-partial/11.jszip.min"%>
<%= render "shared/js-partial/12.pdfmake.min"%>
<%= render "shared/js-partial/13.vfs_fonts"%>
<%= render "shared/js-partial/14.buttons.html5.min"%>
<%= render "shared/js-partial/15.buttons.print.min"%>
<%= render "shared/js-partial/16.buttons.cloVis.min"%>
<%= render "shared/js-partial/17.dataTables.responsive.min"%>
<%= render "shared/js-partial/18.responsive.bootstrap4.min"%>
<%= render "shared/js-partial/19.datatables.init"%>
<%= render "shared/js-partial/20.app"%>