config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  namespace :admin do
    root "dashboard#index"
    get "dashboard" => "dashboard#index", :as => :dashboard
    devise_scope :user do
      get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
      get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration

    end

    devise_for :users, controllers: { sessions: 'admin/users/sessions'}, :passwords => 'admin/users/passwords', :skip => [:registrations]

    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users' => 'devise/registrations#update', :as => 'user_registration'
      patch 'users' => 'devise/registrations#update', :as => 'update_user_registration'
    end

    resources :blogs
    resources :products
    resources :properties
    resources :prototypes

    namespace :changes do
      resources :products do
        resource :property,only: [:edit, :update]
      end
    end
    
    namespace :multi do
      resources :products do
        resource :variant, only: [:edit, :update]
      end
    end


  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/variant.rb
class Variant < ApplicationRecord
  before_save :update_slug
  #Relationship
  has_many :product_variants
  has_many :products, through: :product_variants
  
  belongs_to :user, required: false

  def update_slug
    self.slug = sku.parameterize
  end

  def to_param
    slug
  end
end

app/controllers/admin/multi/variants_controller.rb
class Admin::Multi::VariantsController < ApplicationController
  before_action :authenticate_admin_user!
  before_action :admin_only?
  helper_method :all_variants
  before_action :set_variant, only: [:show,:edit,:update,:destroy]

  def edit
    if !@product.product_variants.exists?
      @product.product_variants.build
    end
  end

  def update
    if @product.update_attributes(variant_params)
      flash[:notice] = "Successfully Updated Variant."
      redirect_to admin_product_path(@product.slug)
    else
      render :edit
    end
  end

  private
    def admin_only?
      unless current_admin_user.admin?
        unless @user == current_admin_user
          redirect_to admin_dashboard_path, :alert => "You cannot access to this section"
        end
      end
    end

    def variant_params
      params.require(:product).permit!
    end

    def all_variants
      @all_variants  ||= Variant.all.map { |v| [v.sku, v.id]}
    end

    def set_variant
      @product = Product.find_by_slug(params[:product_id])
    end
end

app/views/admin/multi/variants/_product_variant_fields.html.erb
  <div class="nested-fields product-variants-fields col-lg-6">
    <%=link_to_remove_association "Remove", f , class: "btn btn-danger"%>

    <div class="form-group">
      <%=f.label :sku%>
      <%=f.text_field :sku, :class=>"form-control"%>
    </div>
    <div class="form-group">
      <%=f.label :name%>
      <%=f.text_field :name, :class=>"form-control"%>
    </div>
    <div class="form-group">
      <%=f.label :price%>
      <%=f.text_field :price, :class=>"form-control"%>
    </div>
    <div class="form-group">
      <%=f.label :cost%>
      <%=f.text_field :cost, :class=>"form-control"%>
    </div>

  </div>

app/views/admin/multi/variants/edit.html.erb
<%= render "components/header"%>

<div class="wrapper">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
              <div class="page-title-box">
                <h4 class="page-title">Form Property</h4>
              </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="card m-b-20">
                    <div class="card-block">
                        <h4 class="mt-0 header-title">Property</h4>
                        <p class="text-muted m-b-30 font-14"></p>
                        <%=form_for([:admin,@product],url: admin_multi_product_variant_path(@product.slug)) do |f|%>
                          <div class="row">
                            <%=f.fields_for :product_variants do |product_variant|%>
                                <%= render 'product_variant_fields', :f => product_variant%>
                            <%end%>
                            <div class="links col-lg-12">
                              <%= link_to_add_association 'New Variant', f, :product_variants, :class=>"btn btn-info"%>
                              <%=f.submit class: "btn btn-info"%>
                            </div>
                          </div>
                          <br>
                        <%end%>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<%= render "components/footer"%>
<%= render "shared/js-partial/1.bootstrap.min"%>
<%= render "shared/js-partial/2.modernizr.min"%>
<%= render "shared/js-partial/3.waves"%>
<%= render "shared/js-partial/4.jquery.slimscroll"%>
<%= render "shared/js-partial/5.jquery.nicescroll"%>
<%= render "shared/js-partial/6.jquery.scrollTo.min"%>
<%= render "shared/js-partial/7.jquery.dataTables.min"%>
<%= render "shared/js-partial/8.dataTables.bootstrap4.min"%>
<%= render "shared/js-partial/9.dataTables.buttons.min"%>
<%= render "shared/js-partial/10.buttons.bootstrap4.min"%>
<%= render "shared/js-partial/11.jszip.min"%>
<%= render "shared/js-partial/12.pdfmake.min"%>
<%= render "shared/js-partial/13.vfs_fonts"%>
<%= render "shared/js-partial/14.buttons.html5.min"%>
<%= render "shared/js-partial/15.buttons.print.min"%>
<%= render "shared/js-partial/16.buttons.cloVis.min"%>
<%= render "shared/js-partial/17.dataTables.responsive.min"%>
<%= render "shared/js-partial/18.responsive.bootstrap4.min"%>
<%= render "shared/js-partial/19.datatables.init"%>
<%= render "shared/js-partial/20.app"%>