config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  namespace :admin do
    root "dashboard#index"
    get "dashboard" => "dashboard#index", :as => :dashboard
    devise_scope :user do
      get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
      get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration

    end

    devise_for :users, controllers: { sessions: 'admin/users/sessions'}, :passwords => 'admin/users/passwords', :skip => [:registrations]

    as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      put 'users' => 'devise/registrations#update', :as => 'user_registration'
      patch 'users' => 'devise/registrations#update', :as => 'update_user_registration'
    end

    resources :blogs
    resources :products
    resources :properties
    resources :prototypes

    namespace :changes do
      resources :products do
        resource :property,only: [:edit, :update]
      end
    end
    
    namespace :multi do
      resources :products do
        resource :variant, only: [:edit, :update]
      end
    end


  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/property.rb
class Property < ApplicationRecord
  before_save :update_slug
  #Relationship
  has_many :prototype_properties
  has_many :protoypes, :through => :prototype_properties

  has_many :product_properties
  has_many :products, through: :product_properties
  
  belongs_to :user, required: false
  validates :identifing_name, presence: true

  def update_slug
    self.slug = identifing_name.parameterize
  end

  def to_param
    slug
  end
end

app/controllers/admin/changes/properties_controller.rb
class Admin::Changes::PropertiesController < ApplicationController
  before_action :authenticate_admin_user!
  before_action :admin_only?
  helper_method :all_properties
  before_action :set_product, only: [:edit, :update]

  def edit
    if !@product.product_properties.exists?
      @product.product_properties.build
    end
  end

  def update
    if @product.update_attributes(property_params)
      flash[:notice] = "Successfully updated properties."
      redirect_to admin_product_path(@product.slug)
    else
      render :edit
    end
  end
  private
    def admin_only?
      unless current_admin_user.admin?
        unless @user == current_admin_user
          redirect_to admin_dashboard_path, :alert => "You can not access to this page"
        end
      end
    end

    def property_params
      params.required(:product).permit!
    end

    def all_properties
      @all_properties ||= Property.all.map { |p| [p.identifing_name, p.id]}
    end

    def set_product
      @product = Product.find_by_slug(params[:product_id])
    end
end

app/controllers/admin/properties_controller.rb
class Admin::PropertiesController < ApplicationController
  before_action :authenticate_admin_user!
  before_action :admin_only?
  before_action :set_property, only: [:show,:edit,:update,:destroy]

  def index
    @properties = Property.all.order(id: :desc)
  end

  def show

  end

  def new
    @property = current_admin_user.properties.build
  end

  def create
    @property = current_admin_user.properties.build(property_params)
    if @property.save
      redirect_to admin_property_path(@property), notice: "Successfully Created"
    else
      flash[:error] = "The property could not be saved"
      render :new
    end
  end

  private
    def admin_only?
      unless current_admin_user.admin?
        unless @user == current_admin_user
          redirect_to admin_dashboard_path, notice: "You're not able to access this page"
        end
      end
    end

    def set_property
      @property = Property.find_by_slug(params[:id])
    end

    def property_params
      params.required(:property).permit(:identifing_name,:display_name,:user_id)
    end
end

app/views/admin/properties/_form.html.erb
<div class="wrapper">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
              <div class="page-title-box">
                <h4 class="page-title">Form Property</h4>
              </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="card m-b-20">
                    <div class="card-block">
                        <h4 class="mt-0 header-title">Property</h4>
                        <p class="text-muted m-b-30 font-14"></p>
                        <%=form_for([:admin, @property]) do |f|%>
                            <div class="form-group col-lg-6">
                              <%=f.label :identifing_name%>
                              <%=f.text_field :identifing_name,class: "form-control", placeholder: "Identifing Name"%>
                            </div>
                            <div class="form-group col-lg-6">
                              <%=f.label :display_name%>
                              <%=f.text_field :display_name,class: "form-control", placeholder: "Identifing Name"%>
                            </div>
                            <div class="form-group col-lg-6">
                              <div>
                                <%=f.submit "Save", class: "btn btn-info"%>

                                <%=link_to "Cancel", admin_properties_path, :class => "btn btn-dark"%>
                              </div>
                          </div>
                        <%end%>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/admin/properties/_property_detail.html.erb
<div class="wrapper">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
              <div class="page-title-box">
                <h4 class="page-title"><%=@property.display_name%></h4>
              </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="card m-b-20">
                    <div class="card-block">
                        <h4 class="mt-0 header-title">Property Detail</h4>
                        <!-- Detail Here -->
                        <%=link_to "Edit", edit_admin_property_path, class: "btn btn-info"%>
                        <%=link_to "Cancel", admin_properties_path, class: "btn btn-dark"%>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/admin/properties/_table_property.html.erb
<div class="wrapper">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                  <div class="page-title-box">
                    <div class="btn-group pull-right">
                      <%=link_to "Add New Property", new_admin_property_path, class: "btn btn-large btn-info" %>
                    </div>
                    <h4 class="page-title">Products</h4>
                  </div>
                </div>
            </div>

            <div class="row">
                <div class="col-12">
                    <div class="card m-b-20">
                        <div class="card-block">
                          <h4 class="mt-0 header-title">Products Table</h4>
                            <p class="text-muted m-b-30 font-14"></p>
                            <table id="datatable-buttons" class="table table-striped table-bordered" cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th>Identifing Name</th>
                                        <th>Display Name</th>
                                        <th>Status</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                  <%@properties.each do |property|%>
                                    <tr>
                                      <td><%=property.identifing_name%></td>
                                      <td><%=property.display_name%></td>
                                      <td><%=status_converter(property.active)%></td>
                                      <td>
                                        <%=link_to "View", admin_property_path(property)%>
                                        <%=link_to "Edit", edit_admin_property_path(property)%>
                                        <%=link_to "Delete", admin_property_path(property), method: :delete, data: {confirm: "Are You Sure ?"}%>
                                      </td>

                                    </tr>
                                  <%end%>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

app/views/admin/properties/edit.html.erb
<%= render "components/header"%>

<%=render "form"%>

<%= render "components/footer"%>

<%= render "shared/js-partial/1.bootstrap.min"%>
<%= render "shared/js-partial/2.modernizr.min"%>
<%= render "shared/js-partial/3.waves"%>
<%= render "shared/js-partial/4.jquery.slimscroll"%>
<%= render "shared/js-partial/5.jquery.nicescroll"%>
<%= render "shared/js-partial/6.jquery.scrollTo.min"%>
<%= render "shared/js-partial/7.jquery.dataTables.min"%>
<%= render "shared/js-partial/8.dataTables.bootstrap4.min"%>
<%= render "shared/js-partial/9.dataTables.buttons.min"%>
<%= render "shared/js-partial/10.buttons.bootstrap4.min"%>
<%= render "shared/js-partial/11.jszip.min"%>
<%= render "shared/js-partial/12.pdfmake.min"%>
<%= render "shared/js-partial/13.vfs_fonts"%>
<%= render "shared/js-partial/14.buttons.html5.min"%>
<%= render "shared/js-partial/15.buttons.print.min"%>
<%= render "shared/js-partial/16.buttons.cloVis.min"%>
<%= render "shared/js-partial/17.dataTables.responsive.min"%>
<%= render "shared/js-partial/18.responsive.bootstrap4.min"%>
<%= render "shared/js-partial/19.datatables.init"%>
<%= render "shared/js-partial/20.app"%>

app/views/admin/properties/index.html.erb
<%= render "components/header"%>

<%= render "table_property"%>

<%= render "components/footer"%>

<%= render "shared/js-partial/1.bootstrap.min"%>
<%= render "shared/js-partial/2.modernizr.min"%>
<%= render "shared/js-partial/3.waves"%>
<%= render "shared/js-partial/4.jquery.slimscroll"%>
<%= render "shared/js-partial/5.jquery.nicescroll"%>
<%= render "shared/js-partial/6.jquery.scrollTo.min"%>
<%= render "shared/js-partial/7.jquery.dataTables.min"%>
<%= render "shared/js-partial/8.dataTables.bootstrap4.min"%>
<%= render "shared/js-partial/9.dataTables.buttons.min"%>
<%= render "shared/js-partial/10.buttons.bootstrap4.min"%>
<%= render "shared/js-partial/11.jszip.min"%>
<%= render "shared/js-partial/12.pdfmake.min"%>
<%= render "shared/js-partial/13.vfs_fonts"%>
<%= render "shared/js-partial/14.buttons.html5.min"%>
<%= render "shared/js-partial/15.buttons.print.min"%>
<%= render "shared/js-partial/16.buttons.cloVis.min"%>
<%= render "shared/js-partial/17.dataTables.responsive.min"%>
<%= render "shared/js-partial/18.responsive.bootstrap4.min"%>
<%= render "shared/js-partial/19.datatables.init"%>
<%= render "shared/js-partial/20.app"%>

app/views/admin/properties/new.html.erb
<%= render "components/header"%>

<%=render "form"%>

<%= render "components/footer"%>

<%= render "shared/js-partial/1.bootstrap.min"%>
<%= render "shared/js-partial/2.modernizr.min"%>
<%= render "shared/js-partial/3.waves"%>
<%= render "shared/js-partial/4.jquery.slimscroll"%>
<%= render "shared/js-partial/5.jquery.nicescroll"%>
<%= render "shared/js-partial/6.jquery.scrollTo.min"%>
<%= render "shared/js-partial/7.jquery.dataTables.min"%>
<%= render "shared/js-partial/8.dataTables.bootstrap4.min"%>
<%= render "shared/js-partial/9.dataTables.buttons.min"%>
<%= render "shared/js-partial/10.buttons.bootstrap4.min"%>
<%= render "shared/js-partial/11.jszip.min"%>
<%= render "shared/js-partial/12.pdfmake.min"%>
<%= render "shared/js-partial/13.vfs_fonts"%>
<%= render "shared/js-partial/14.buttons.html5.min"%>
<%= render "shared/js-partial/15.buttons.print.min"%>
<%= render "shared/js-partial/16.buttons.cloVis.min"%>
<%= render "shared/js-partial/17.dataTables.responsive.min"%>
<%= render "shared/js-partial/18.responsive.bootstrap4.min"%>
<%= render "shared/js-partial/19.datatables.init"%>
<%= render "shared/js-partial/20.app"%>

app/views/admin/properties/show.html.erb
<%= render "components/header"%>

<%= render "property_detail"%>

<%= render "components/footer"%>

<%= render "shared/js-partial/1.bootstrap.min"%>
<%= render "shared/js-partial/2.modernizr.min"%>
<%= render "shared/js-partial/3.waves"%>
<%= render "shared/js-partial/4.jquery.slimscroll"%>
<%= render "shared/js-partial/5.jquery.nicescroll"%>
<%= render "shared/js-partial/6.jquery.scrollTo.min"%>
<%= render "shared/js-partial/7.jquery.dataTables.min"%>
<%= render "shared/js-partial/8.dataTables.bootstrap4.min"%>
<%= render "shared/js-partial/9.dataTables.buttons.min"%>
<%= render "shared/js-partial/10.buttons.bootstrap4.min"%>
<%= render "shared/js-partial/11.jszip.min"%>
<%= render "shared/js-partial/12.pdfmake.min"%>
<%= render "shared/js-partial/13.vfs_fonts"%>
<%= render "shared/js-partial/14.buttons.html5.min"%>
<%= render "shared/js-partial/15.buttons.print.min"%>
<%= render "shared/js-partial/16.buttons.cloVis.min"%>
<%= render "shared/js-partial/17.dataTables.responsive.min"%>
<%= render "shared/js-partial/18.responsive.bootstrap4.min"%>
<%= render "shared/js-partial/19.datatables.init"%>
<%= render "shared/js-partial/20.app"%>